<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => '927cc6c9ce91af31a3edcea2fa4ac799',
  'DATABASE_URL' => 'mysql://sotu3646_legendarift:securedpassword3393@localhost:3306/sotu3646_legendarift?serverVersion=10.6.19-MariaDB&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'native://default',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);